name: Continuous Release
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build

      - run: pnpm dlx pkg-pr-new publish
